version: '3.4'

services:
  postgres-db:
    image: 'postgres:14.1'
#    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB --username=$$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    container_name: postgres-quarkus
    environment:
      - POSTGRES_USER=quarkus_user
      - POSTGRES_PASSWORD=quarkus_test
      - POSTGRES_DB=quarkus_test

  mysql-db:
    image: 'mysql:8.0'
#    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
#    cap_add:
#      - SYS_NICE
    ports:
      - '3306:3306'
    container_name: mysql-quarkus
    environment:
      MYSQL_DATABASE: "quarkus_test"
      MYSQL_USER: "quarkus_user"
      MYSQL_PASSWORD: "quarkus_test"
      MYSQL_ROOT_PASSWORD: "quarkus_test"


  mongo-db:
    image: 'mongo:6.0'
    command: mongod --quiet --logpath /dev/null
    #    restart: always
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - '27017:27017'
    container_name: mongo-quarkus
    environment:
      MONGO_INITDB_ROOT_USERNAME: "quarkus_user"
      MONGO_INITDB_ROOT_PASSWORD: "quarkus_test"
      MONGO_INITDB_DATABASE: "quarkus_test"




